### ISSUE TITLE
The button to maximize the window does not work

### ISSUE THREAD

**Issue by st3no** [mayuso/JMarkPad#37]
When the button is clicked to maximize the window, this changes icon, but the window does not resize itself.

![screenshot_2018-08-04_09-13-08](https://user-images.githubusercontent.com/18469924/43673612-6c41b324-97c6-11e8-9f40-13e06e914b73.png)

It's a bug by JMarkPad or JFoenix??

**Comment by mayuso** [comment]
I can't reproduce this problem, it works for me.

Can you please tell me what did you do? How can I reproduce it?

**Comment by st3no** [comment]
I followed this steps!

1. git clone git@github.com:mayuso/JMarkPad.git
2. cd JMarkPad
3. git checkout develop
4. ./gradlew jfxRun
5. click maximize button

Which OS is installed on your machine?? (i use Linux)

**Comment by mayuso** [comment]
I currently have Windows 10.

That might be the problem. Might need to install a VM to test this on Linux bases OSs too.

**Comment by st3no** [comment]
This seems to fix the bug.

`decorator.setCustomMaximize(true);`
